"""empty message

Revision ID: e13b3b29099d
Revises: b7ff93776f64
Create Date: 2022-08-03 17:36:45.086788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13b3b29099d'
down_revision = 'b7ff93776f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('todo', sa.Column('todolist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo', 'todolist', ['todolist_id'], ['id'])
    # ### end Alembic commands ###
    op.execute("INSERT INTO todolist(id,name) VALUES(1,'Uncategorized')")
    op.execute("UPDATE todo set todolist_id = 1 WHERE todolist_id is NULL")
    op.alter_column('todo','todolist_id',nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'todolist_id')
    op.drop_table('todolist')
    # ### end Alembic commands ###
